### DISCUSSION TITLE
Arguments not passed in pre-commit setup

### DISCUSSION THREAD

**Discussion by pantelis-karamolegkos** [gitleaks/gitleaks#1873] [Q&A] [answered]
In the following setup of `.pre-commit-config.yaml`

```yaml
repos:
  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.26.0
    hooks:
    - id: gitleaks
    - args: [--config=.gitleaks.toml]
```

I get the following warning / error

```
An error has occurred: InvalidConfigError: 
==> File .pre-commit-config.yaml
==> At Config()
==> At key: repos
==> At Repository(repo='https://github.com/gitleaks/gitleaks')
==> At key: hooks
==> At Hook(id=MISSING)
=====> Missing required key: id
Check the log at /some/path/.cache/pre-commit/pre-commit.log
```

What is the correct way to format the entry

**Comment by brahimeelhamed** [comment, marked as answer]
The `args` line is a separate list item instead of being nested under the `id: gitleaks` hook, which is why pre-commit sees it as its own hook entry missing a required `id`. Each `-` under `hooks:` is one hook config, so `args` needs to be indented under the same entry as `id: gitleaks`, not as a sibling:

```yaml
repos:
  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.26.0
    hooks:
      - id: gitleaks
        args: [--config=.gitleaks.toml]
```

Your version parses as two separate hook entries — `{id: gitleaks}` and `{args: [...]}` — and the second one fails validation because it has no `id`.

Also worth knowing: if `.gitleaks.toml` sits at the root of the repo being scanned, you don't actually need `--config` at all — gitleaks auto-detects a `.gitleaks.toml` in the target path by default (see the config precedence section in the README). `args` is only needed if your config lives somewhere else or is named differently.
