### DISCUSSION TITLE
Allowlist rule does not exempt specific pattern

### DISCUSSION THREAD

**Discussion by pantelis-karamolegkos** [gitleaks/gitleaks#1877] [Q&A]
I have a false positive detection of the following string

```
my_weird_string_is_this = "1f45ft5o-99ja-e3ol-1v7b-9s1b1c559f2f"
```

This is captured by the generic API key rule.

Adding the following in `.gitleaks.toml`

```
[[allowlists]]
description = "Exclude my weird string"
regexes = [
    '''(?i)my_weird_string_is_this\s*=\s*.*'''
]
```

does not help since I get

```
gitleaks dir myfile --config .gitleaks.toml

    ○
    │╲
    │ ○
    ○ ░
    ░    gitleaks

10:37AM INF scanned ~69 bytes (69 bytes) in 2.43ms
10:37AM WRN leaks found: 1
```

Regardless of the `allowlists` entry / regex not working (for which I would also appreciate your help / feedback), what is the best / recommended practice to go about this? A stand-alone `allowlists` entry as above or overriding the `generic-api-key` with a `[[rules.allowlist]]`?

Thanks in advance for your help

**Comment by ideacatlab** [comment]
The reason your allowlist does nothing is that `regexes` is matched against the **secret** — the captured value — not the whole line. Your pattern `my_weird_string_is_this\s*=\s*.*` describes the line, but gitleaks only ever tests it against the extracted secret (the UUID-looking part), so it never matches and nothing is exempted.

I reproduced this on 8.30.1. Using a value that reliably trips `generic-api-key`:

```
api_key = "aH9kLmZ2pQ7rT4wX1yB6cV8nD3fG5jS0abc"
```

Your style of allowlist (a line-shaped regex, default target) leaves it detected:

```toml
[extend]
useDefault = true
[[allowlists]]
regexes = ['''api_key\s*=\s*".*"''']   # tested against the secret -> never matches
```
```
WRN leaks found: 1
```

Any of these three fix it — pick by what you actually want to exempt:

**1. Exempt that specific secret value** (narrowest, safest):

```toml
[extend]
useDefault = true
[[allowlists]]
regexes = ['''1f45ft5o-99ja-e3ol-1v7b-9s1b1c559f2f''']
```

**2. Keep your line-shaped regex, but point it at the line** with `regexTarget`:

```toml
[extend]
useDefault = true
[[allowlists]]
regexTarget = "line"                    # or "match" for the full match string
regexes = ['''my_weird_string_is_this\s*=\s*".*"''']
```

Both give `no leaks found`. `regexTarget` accepts `secret` (default), `match`, or `line`.

**3. If the string only ever lives in one file** (fixtures, test data), allowlist the path instead — cleaner than chasing the value:

```toml
[extend]
useDefault = true
[[allowlists]]
paths = ['''.*testfixtures?\.go$''']
```

On your "standalone `[[allowlists]]` vs `[[rules.allowlist]]`" question: use a top-level `[[allowlists]]` (global) when the string is a known-safe value or file anywhere in the repo — which is your case. Use a rule-scoped allowlist only when you specifically want to loosen *one* rule while leaving every other rule free to flag the same text. For a single false positive, global is the right call and what I'd recommend.

One thing worth checking before you add any config: your original example (`1f45ft5o-99ja-e3ol-1v7b-9s1b1c559f2f`, and a key name with no `key`/`token`/`secret`/`api` word in it) does **not** trip `generic-api-key` on 8.30.1 at all — I get `no leaks found` with default rules and no config. `generic-api-key` has been tightened since. If you're on an older gitleaks, upgrading may make the false positive disappear on its own and save you the allowlist entirely. Worth confirming which version your CI runs.

Also note: a bare custom `--config` file **replaces** the default ruleset — that's why your config alone reports no leaks (it drops `generic-api-key` entirely). Keep `[extend] useDefault = true` at the top or you lose all the built-in rules, which is a different and worse surprise.
