### ISSUE TITLE
Detect nuget passwords

### ISSUE THREAD

**Issue by lattera** [gitleaks/gitleaks#1147]
**Is your feature request related to a problem? Please describe.**

I'm working on a customer pentest engagement wherein we found in the project's build scripts a command to add a custom NuGet repo to Visual Studio, where the repo is protected by username and password authentication.

**Describe the solution you'd like**

I think gitleaks might be well to detect NuGet repo authentication credential leakage.

**Describe alternatives you've considered**

I'm not sure there are alternatives to consider, but I'm open to discussing my blind spots. :-)

**Additional context**

Here's a sample (redacted) command: `nuget.exe source Add -Name "ProprietaryRepo" -source "https://..." -username "yup_username_leak_here" -password "hashed_password_leak_here"`

cc @zricethezav

**Comment by rgmz** [comment]
Great suggestion! I am in the process of compiling a bunch of patterns myself, so I figured I'd take a crack at this.

Here's a naive rule you can try. I haven't thoroughly tested this but it should match both [`nuget sources add`](https://learn.microsoft.com/en-us/nuget/reference/cli-reference/cli-ref-sources) and [`dotnet nuget add source`](https://learn.microsoft.com/en-us/dotnet/core/tools/dotnet-nuget-add-source) (https://regex101.com/r/yGV6CJ/1).

```toml
[[rules]]
id = "nuget-source-password"
regex = '''(?i)nuget(?:\.exe)?\s+(?:sources\s+add|add\s+sources)\s+.+\s-password\s*("[^"]+"|[^\s]+)'''
secretGroup = 1
keywords = ["nuget.exe", "nuget"]
```

Feel free to play around with this and [open a pull request](https://github.com/gitleaks/gitleaks/blob/master/CONTRIBUTING.md#adding-new-gitleaks-rules) if this works for you.
