### ISSUE TITLE
Allowlist `regexTarget` checks entire match, not just the secret

### ISSUE THREAD

**Issue by rgmz** [gitleaks/gitleaks#1151]
**Describe the bug**

The documentation for `rules.allowlist.regexTarget` explains that `rules.allowlist.regexes` checks the secret by default:

> note: (rule) regexTarget defaults to check the _Secret_ in the finding.
> if regexTarget is not specified then _Secret_ will be used.
> Acceptable values for regexTarget are "match" and "line"

However, because the allowlist check happens before the secret is extracted from the match group this can behave in an unexpected way.

https://github.com/gitleaks/gitleaks/blob/839f114f2b2ca9429300e545aa5c93a2caf2e3d8/detect/detect.go#L290-L297

https://github.com/gitleaks/gitleaks/blob/839f114f2b2ca9429300e545aa5c93a2caf2e3d8/detect/detect.go#L311-L320

**To Reproduce**

Consider the following (admittedly contrived and over-complicated) rule and file.

**Rule**

```toml
[[rules]]
id = "spring-vault-token-yaml"
description = "Spring vault token"
regex = '''(?mi)(?:config:(?:\s|.)+?|vault:(?:\s|.)+?|config\.|vault\.)token\s*?:\s?(.+)$'''
secretGroup = 1
path = '''(?i)\.ya?ml$'''

[rules.allowlist]
regexes = ['''(?mi)\${[^:}]+}$'''']
```
**File**
```yml
#application.yml
spring:
  cloud:
    vault:
      kv:
        enabled: true
        application-name: ${spring.application.name}

      # root token
      token: hvs.WzBcwSIguZzLnhfJmPaCIMnK
```

Running GitLeaks will yield no results, because it will check the entire match and the regex `(?mi)\${[^:}]+}$` matches `${spring.application.name}`:

```sh
$ gitleaks detect --no-banner --config ./gitleaks.toml --no-git --verbose --source application2.yml
1:13PM INF scan completed in 11.8ms
1:13PM INF no leaks found
```

**Expected behavior**

The secret should be extracted from the match group prior to testing the allowlist regexes, at least when `secret` (i.e., nothing) is specified for `regexTarget`

cc @zricethezav
