### ISSUE TITLE
basic auth not detected

### ISSUE THREAD

**Issue by tooptoop4** [gitleaks/gitleaks#1203]
'Authorization': 'Basic redactedrealstring==',

**Comment by pcrock-thmdo** [comment]
I created the following rule and tested it on about 100 repos (some private repos, and some well-known open source projects). I found about 30 leaks, and not a single one was a false positive.

```toml
[[rules]]
id = "http-basic-auth-header"
description = "Detected HTTP Basic Authorization header"
# regex based on https://developer.mozilla.org/en-US/docs/Glossary/Base64
regex = '''(?:Basic)\s([A-Za-z0-9\+/\=\-_]+)'''
entropy = 3.5
keywords = [
  "Basic",
]
```

The `entropy` value there is pretty important for cutting back false positives. I'm unsure if that meets the standards for being included as a default rule, but it seems at least _fairly_ robust.
