### ISSUE TITLE
Detect Kubernetes Secrets

### ISSUE THREAD

**Issue by guettli** [gitleaks/gitleaks#1227]
I would like to detect yaml files which contain Kubernetes secrets:

```
apiVersion: v1
data:
  foo: |
    YWMzN2Iy....
kind: Secret
metadata:
  name: foo
type: Opaque
```

cc @zricethezav
