### ISSUE TITLE
How do I scan files inside a folder?

### ISSUE THREAD

**Issue by marcelo321** [gitleaks/gitleaks#1282]
```
$ gitleaks detect -s ~/ubuntu/leak-scan/results/folder

    ○
    │╲
    │ ○
    ○ ░
    ░    gitleaks

6:04AM ERR [git] fatal: not a git repository (or any of the parent directories): .git
6:04AM ERR  error="stderr is not empty"
6:04AM WRN partial scan completed in 12.6ms
6:04AM WRN no leaks found in partial scan
```

I am not trying to scan github repositories, would be possible to scan files? shouldn't make any difference in the scan at all, it should check leaks in files/folders.

**Comment by radoslav-stefanov** [comment]
What about if using actions? I am trying to set it up in a composite action and I need to scan a custom directory.

```yaml
name: Gitleaks
description: Gitleaks scan

inputs:
  fetch-depth:
    required: false
    description: 'Number of commits to fetch during checkout. 0 indicates all history for all branches and tags'
    default: '1'

runs:
  using: "composite"
  steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        path: code
        fetch-depth: ${{ inputs.fetch-depth }}

    - uses: gitleaks/gitleaks-action@v2
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
        GITLEAKS_LICENSE: ${{ inputs.gitleaks_license }}
 ```
