### ISSUE TITLE
stopwords conflict with regex

### ISSUE THREAD

**Issue by heang-github** [gitleaks/gitleaks#1303]
Please correct me I am wrong.

**Describe the bug**
Here is our default rule for facebook
````toml
[[rules]]
id = "facebook"
description = "Facebook Access Token"
regex = '''(?i)(?:facebook)(?:[0-9a-z\-_\t .]{0,20})(?:[\s|']|[\s|"]){0,3}(?:=|>|:{1,3}=|\|\|:|<=|=>|:|\?=)(?:'|\"|\s|=|\x60){0,5}([a-f0-9]{32})(?:['|\"|\n|\r|\s|\x60|;]|$)'''
keywords = [
    "facebook",
]
````

I notice that our stopwords slice include "facebook" too. 

````toml
[rules.allowlist]
stopwords = ["facebook"]
````

I wonder if the stopword conflict with the regex ? I saw something similar for twitter, linkedin, etc. 

**Basic Info (please complete the following information):**
 - OS: mac
 - Gitleaks Version:8.18.1
