### ISSUE TITLE
Simple example needed on how to ignore or whitelist a directory

### ISSUE THREAD

**Issue by huornlmj** [gitleaks/gitleaks#1328]
I've spent around 30 mins reading and searching on how to ignore s /tests/ directory and I have failed.  Can someone share info on how this is done?

**Comment by discodane** [comment]
Same. It seems the example ignore file lists out each file individually.

**Comment by gregorysprenger** [comment]
I've spent way too long on this. The documentation is confusing, where the `allowlist` is used to ignore paths/regexes.

I have the following in `gitleaks.toml`:
```
[allowlist]
paths = [
  '''bin/'''
]
```

And then you have to directly pass the `gitleaks.toml` file gitleaks detect like so:
```
gitleaks detect --config /path/to/gitleaks.toml
```

**Comment by enkelmedia** [comment]
For me,

```
[allowlist]
paths = [
  '''bin/'''
]
```

Would only scan the "bin" folder which is strange.

**Comment by JulesdeCube** [comment]
Hello,

had the same issue. You need to specify:

```toml
[extend]                                                                        
useDefault = true
```

Otherwise gitleak will have no rule to match.

You can use the following configuration to exclude file under `./my/folder`:

```toml
[extend]
useDefault = true

[[allowlists]]
paths = [
    '''^my/folder/'''
]
```
