### ISSUE TITLE
Declare API keys with checksums

### ISSUE THREAD

**Issue by fgreinacher** [gitleaks/gitleaks#1456]
**Is your feature request related to a problem? Please describe.**

Some API keys include checksums in order to:

1. allow quick validation of a provided API keys before hitting the database
2. prevent false positives in public secret scanning infrastructure like [GitHub Secret Scanning](https://docs.github.com/en/code-security/secret-scanning/secret-scanning-partner-program#identify-your-secrets-and-create-regular-expressions)

It would be great if Gitleaks knew about checksums to reduce false positives.

**Describe the solution you'd like**

Assuming we have an API key that consists of a a prefix, following by 25 characters of entropy, following by an hex-encoded Adler-32 checksum, we could express this in the ruleset:

```toml
[[rules]]
id = "my-api-key"
regex = '''MY-PREFIX-[0-9a-zA-Z]{32}'''

[rules.checksum]
# Algorithm and encoding are sufficient to extract the checksum if we assume it is at the end of the secret
algorithm = "adler-32"
encoding = "hex"

# If the checksum is not at the end we might later allow extracting it via a regex pattern:
regex = '''MY-PREFIX-[0-9a-zA-Z]{25}([0-9a-f]{8})'''

```

**Describe alternatives you've considered**

Relying only on the regex works, but can produce quite some false positives depending on the prefix.

**Additional context**

-

cc @zricethezav
