### ISSUE TITLE
Additional Kubernetes Secret Detections

### ISSUE THREAD

**Issue by rgmz** [gitleaks/gitleaks#1513]
**1. Kubernetes Secrets as JSON**

#1462 covers YAML but not JSON.

**2. Detect StringData Secrets**

> Add a rule for [stringData](https://kubernetes.io/docs/concepts/configuration/secret/#docker-config-secrets) in the future.

_Originally posted by @rgmz in https://github.com/gitleaks/gitleaks/issues/1462

**3. Other types of secret resources**

> It might be interesting to add a rule for special resources such as ExternalSecret or SopsSecrets and work on an absence of special characters. For example, one could flag an ExternalSecret resource if for each key within the spec.target.template.data field "{{" and "}}" are missing. Similarly, for SopsSecret it would be sufficient to check for the "sops:" field. Of course, you could also add a custom .gitleaks.toml for these personal usecases.

> Would like to hear your thoughts about this.

_Originally posted by @marcm-ml in https://github.com/gitleaks/gitleaks/issues/1462#issuecomment-2357853798_

**Comment by marcm-ml** [comment]
Answering here regarding examples for other types of secret resources:

Re: `kind: ExternalSecrets`
The only real place a secret value could be used is in the `spec.target.template.data` field as every other field is either metadata or a reference of a secret inside a vault.
Here are some examples of real positives and false positives(... indicate that there exist irrelevant fields). I added all the examples to one resource definition for brevity, but any number of fields can be added to the spec.target.template.data fiel.

```yaml
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata: ...
spec:
  ...
  # this would usually not contain secret data only references to secrets inside vaults, hence it should not be matched
  data: ... 
  # this would usually not contain secret data only references to secrets inside vaults, hence it should not be matched
  dataFrom: ...
  target:
    ...
    template:
      ...
      # this is the only place a secret could possibly be added and serve a purpose
      data:
        # true positive
        password1: my-password
        # true positive
        password2: |
          another-password
        # false positive -- this is only a reference. references are always go-templates
        password3: "{{ .password }}"
        # false positive
        password4: >
          "{{ .password }}"
        # false positive
        password5: "https://username:{{ .password }}@url.com"
        # false positive
        password6: |-
          "https://username:{{ .password }}@url.com"
      templateFrom: ...
```

Re: SopsSecret
A k8s resource of kind SopsSecret is basically a sops-encrypted secret where only special fields (`data`, `stringData` or `secretTemplates`) are encrypted and decrypted on-the-fly by the sops operator living in the k8s clusters. It should be sufficient to either extend the current kubernets-secret rule by also matching for `kind:[\t ]*(sops)?secret` or create a new rule and only match for `kind: SopsSecret`.
