### ISSUE TITLE
Allowlists not working 

### ISSUE THREAD

**Issue by ahoehma** [gitleaks/gitleaks#1590]
**Describe the bug**
I defined allowlists to ignore all the xml/log/json files.

**To Reproduce**

.gitleaks.toml with

```
[extend]
useDefault = true

[[rules]]

[allowlists]
paths = ['^.*\.(xml|log|json)$']

[[rules.allowlists]]
paths = ['^.*\.(xml|log|json)$']
```

Note: I tried both 

```
[[rules.allowlists]]
```

and

```
[[rules]]

[allowlists]
```

gitleaks detect -c .gitleaks.toml --redact --no-git --verbose --source .

**Expected behavior**
No findings in these files, doesn't matter where they are located.

**Basic Info (please complete the following information):**
 - OS: windows/gitbash
 - Gitleaks Version: 8.21.0

cc @zricethezav

**Comment by rgmz** [comment]
@ahoehma Neither example is a valid config, I'd suggest reviewing [the README](https://github.com/gitleaks/gitleaks?tab=readme-ov-file#configuration) for proper syntax.
```toml
[[rules]] <--- Can't be used without an `id`

[allowlists] <--- Doesn't exist. 
paths = ['^.*\.(xml|log|json)$']

[[rules.allowlists]]
paths = ['^.*\.(xml|log|json)$']
```

It's a bug that you didn't receive a config validation error for using `[[rules]]` without `id`. I opened #1592 to address that.
