### ISSUE TITLE
Organisation key email never received

### ISSUE THREAD

**Issue by anthonyseager** [gitleaks/gitleaks#1624]
**Describe the bug**
The _Free Organization License Key_ is never received via email after completing the sign up google form.
I have tried this on Gmail and a work email.

**To Reproduce**
Go to https://gitleaks.io/ and complete the form after clicking sign up under _Free Organization License Key_

**Expected behavior**
The email to be sent

**Screenshots**
N/A

**Basic Info (please complete the following information):**
 - OS: N/A
 - Gitleaks Verion: N/A

**Additional context**
N/A

cc @zricethezav

**Comment by ImanSM** [comment]
Is there an alternative way to get the _Free Organization License Key_ while the form is being repaired?

**Comment by serpro69** [comment]
Same here. Any chance this can be addressed soon?

**Comment by apbard** [comment]
just leave the license field empty and it will work (I have read somewhere that the check is currently disabled)

**Comment by serpro69** [comment]
> just leave the license field empty and it will work (I have read somewhere that the check is currently disabled)

Leave it empty as in?
I've tried to both remove the env variable completely, as well as giving it an empty string value, and in both cases it errors out with: `🛑 missing gitleaks license. Go grab one at gitleaks.io and store it as a GitHub Secret named GITLEAKS_LICENSE. For more info about the recent breaking update, see [here](https://github.com/gitleaks/gitleaks-action#-announcement).`

**Comment by mfarzamalam** [comment]
I'm still facing this issue. When I tried the solution from @serpro69, it failed too.

Error Detail:
```
Cache restored successfully
Gitleaks restored from cache
event type: pull_request
/home/runner/work/_actions/gitleaks/gitleaks-action/v2/dist/index.js:51503
      const error = new requestError.RequestError(toErrorMessage(data), status, {
                    ^

RequestError [HttpError]: Resource not accessible by integration
    at /home/runner/work/_actions/gitleaks/gitleaks-action/v2/dist/index.js:51503:21
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.ScanPullRequest (/home/runner/work/_actions/gitleaks/gitleaks-action/v2/dist/index.js:129568:17)
    at async start (/home/runner/work/_actions/gitleaks/gitleaks-action/v2/dist/index.js:140770:16) {
  status: 403,

```

**Comment by imgaf** [comment]
I’m experiencing the same issue - I’m seeing the same outcome as @mfarzamalam when setting GITHUB_TOKEN and GITLEAKS_LICENSE.

**Comment by mfarzamalam** [comment]
@imgaf Hey, I've tried version 4 of gitleaks. It’s working as I expected. You can try it too.

```
jobs:
  gitleaks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install gitleaks
        run: |
          curl -sSfL https://github.com/gitleaks/gitleaks/releases/download/v8.21.2/gitleaks_8.21.2_linux_x64.tar.gz | tar -xz
          sudo mv gitleaks /usr/local/bin/
      - name: Scan codebase for secrets
        run: gitleaks detect --source . --no-git --verbose
```
