### ISSUE TITLE
pre-commit hook rev: v8.19.0 `FTL flag accessed but not defined: source`

### ISSUE THREAD

**Issue by trottomv** [gitleaks/gitleaks#1686]
**Describe the bug**
```
  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.19.0
    hooks:
      - id: gitleaks
```

**To Reproduce**
```
git add .
pre-commit run --all-files
```

```
Detect hardcoded secrets.................................................Failed
- hook id: gitleaks
- exit code: 1

○
    │╲
    │ ○
    ○ ░
    ░    gitleaks

11:15AM FTL flag accessed but not defined: source
```

**Basic Info (please complete the following information):**
 - OS: macos
 - Gitleaks Version: pre-commit hook rev: v8.19.0

**Additional context**
This error does not appear with version rev: v8.18.0

cc @zricethezav
