### ISSUE TITLE
K8s Sealed Secrets detected as Generic-Api-Key

### ISSUE THREAD

**Issue by pvillaverde** [gitleaks/gitleaks#1728]
Hey there! First of all, I would like to thank you for this amazing tool, it's really useful.

**Describe the bug**
Since last release (v8.23.2) my pipelines and pre-commit hooks running gitleaks have begun detecting "generic-api-keys" while in all my sealed secrets object definitions.

**To Reproduce**
The first one might be the most difficult, have a k8s cluster. I guess the easiest way is to [setup a minikube for the test following its docs](https://minikube.sigs.k8s.io/docs/start/?arch=%2Flinux%2Fx86-64%2Fstable%2Fbinary+download).

Then, and following the [Sealed Secrets Documentation](https://fluxcd.io/flux/guides/sealed-secrets/), create a simple secret:

Generate a Kubernetes secret manifest with kubectl:

```bash
kubectl -n default create secret generic basic-auth \
--from-literal=user=admin \
--from-literal=password=change-me \
--dry-run=client \
-o yaml > basic-auth.yaml

```
That secret file format(before sealing it), in case you haven't worked with K8s, is like this:
```yaml
apiVersion: v1
data:
  password: Y2hhbmdlLW1l
  user: YWRtaW4=
kind: Secret
metadata:
  creationTimestamp: null
  name: basic-auth
  namespace: default
```
Encrypt the secret with kubeseal:

```bash
kubeseal --format=yaml --cert=pub-sealed-secrets.pem \
< basic-auth.yaml > basic-auth-sealed.yaml
```
Output of that sealed secret is like this:

```yaml
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: basic-auth
  namespace: default
spec:
  encryptedData:
    password: AgAYsM4W6e5MMp90oqj7sIolG+//xxJTwRh8ke50CUFiZ8M/r5BoV/vHh3zKnlskt/s4jK058M1i4Y3ETgfsrbiYD/3ADLKRHjr2TO5O6xUrWtfFh6aDR8fOSbVpm1qCSmxFGMaHq5QLJ3Ab0FQTKF/eFehogkzXb8opY/PlI9r+9DcUJ1epAjbNjzvHDDSEZxwi/i5kCNfxqnQNZHQ4uIgEysOk/kjBEtfISxyeD2PGYiyMYk9zMtEUk9LoUTR3/EXiFcJc4iw83DUVICbaCdMPh2ZRsv3A1CWx608rtIyF+qqKnmfX5me7njnYi0vGVDY97T4cV5rKrdZTTOZVggur2l+sPG+BJSYmEVqz3cZ81mVOr4znwU6w3f2e5HxD7ivdJJEz70xgPFX8pFruQulAOohd8qXakqdtA+ew+tr0h3M+cWvOu6VNXQlbijRgC4R89CclHW4/GX3j0OulJUotrV29rTpmVZ7MTGrnZkwJbNUYAe1GEFo7LNws+GJTcNM9R6QA/AYvJ2eE3SjE2G7VaIUh2RvSe2O094Ln7yIJctzEK8afiCiIQQnIgy/M+YheoC+TzogvLZGuNsvrt/oiiilUNa6WODTr1DmJGIyM4cg0pZuVKJ8dx+zf4l7+efkBOa/2mzU9DakvoRQK8/ClR6tuOAVXHZksPehcI3eTX/ZI0MtM2CLJouoi86hPbgwEorBt+nLClkw=
    user: AgAMrlzJFHS+mqUhv2ZpG57VNoTSRrewuu6FZVPZcV35dCmdZwesz3MSrmweNHXAlJbVMSMRlINIEBQZKgjw0szEh2ZKkXjGv1926p34GJJSB5/rqYBIDUFkIRY3aJsijMN6etjLRQi68sbYIQAZQM4pGdN23++CfNmXoQgDm9ItspcSYAcOeKP8tZ799pQTdM1pMMur5EyrYWxckORCz+OT1+buCL9+5DJkjU7JuQCk5QkwXRE1sm76FvmmP+a3FbNCIgqsBpD42AqqD4/ex0PogKr7gDkG27MWZNIvCWDd2iF4x1cwJgOtNZJEzQ7tDr+Mf4438w03sJQPMtCEUuuzX1I7SPuT6D9eRSV00GA/IS0/fmNbPf2pPHFxj8t1RMsGI2ZLdZBOXapn3P0SLYZ2Xh6QIqdxzb3VR37WS/Ir4c8v86ZzDTbnqVdT/rwb7U4Iy2k3nDj+/ghxD+7HQbmBx4zzFVYe70Sb1QIWthzZHtuvoX7+FeSa6iU6ipUj4g0U9r53vD+AYt7ntJtCI3EdX+Fh9yJe4AAL4ToHjnt3s2EG4K5i0/21KwAy9WX2rkwBb8GD3POT3zZq2b4uB5gUYyF467kw0J7MfEsPJjAfhd72+IMM9BZDU4tlrFBJPRubVsmRJKelM/o1YTkbl+eFNyWBE1t5IQ9DFjHpcppgUm1CUiDdI0RbIc2goHfFWNePxZZQBg==
  template:
    metadata:
      creationTimestamp: null
      name: basic-auth
      namespace: default
```
Then you can debug it running gitleaks like this:

```bash
docker run --rm -it -v .:/app zricethezav/gitleaks:v8.23.2 detect --no-git --source /app/basic-auth-sealed.yaml -r /proc/1/fd/1

    ○
    │╲
    │ ○
    ○ ░
    ░    gitleaks

9:01PM INF scanned ~1721 bytes (1.72 KB) in 115ms
9:01PM WRN leaks found: 1
[
 {
  "RuleID": "generic-api-key",
  "Description": "Detected a Generic API Key, potentially exposing access to various services and sensitive operations.",
  "StartLine": 10,
  "EndLine": 10,
  "StartColumn": 6,
  "EndColumn": 735,
  "Match": "password: AgAYsM4W6e5MMp90oqj7sIolG+//xxJTwRh8ke50CUFiZ8M/r5BoV/vHh3zKnlskt/s4jK058M1i4Y3ETgfsrbiYD/3ADLKRHjr2TO5O6xUrWtfFh6aDR8fOSbVpm1qCSmxFGMaHq5QLJ3Ab0FQTKF/eFehogkzXb8opY/PlI9r+9DcUJ1epAjbNjzvHDDSEZxwi/i5kCNfxqnQNZHQ4uIgEysOk/kjBEtfISxyeD2PGYiyMYk9zMtEUk9LoUTR3/EXiFcJc4iw83DUVICbaCdMPh2ZRsv3A1CWx608rtIyF+qqKnmfX5me7njnYi0vGVDY97T4cV5rKrdZTTOZVggur2l+sPG+BJSYmEVqz3cZ81mVOr4znwU6w3f2e5HxD7ivdJJEz70xgPFX8pFruQulAOohd8qXakqdtA+ew+tr0h3M+cWvOu6VNXQlbijRgC4R89CclHW4/GX3j0OulJUotrV29rTpmVZ7MTGrnZkwJbNUYAe1GEFo7LNws+GJTcNM9R6QA/AYvJ2eE3SjE2G7VaIUh2RvSe2O094Ln7yIJctzEK8afiCiIQQnIgy/M+YheoC+TzogvLZGuNsvrt/oiiilUNa6WODTr1DmJGIyM4cg0pZuVKJ8dx+zf4l7+efkBOa/2mzU9DakvoRQK8/ClR6tuOAVXHZksPehcI3eTX/ZI0MtM2CLJouoi86hPbgwEorBt+nLClkw=",
  "Secret": "AgAYsM4W6e5MMp90oqj7sIolG+//xxJTwRh8ke50CUFiZ8M/r5BoV/vHh3zKnlskt/s4jK058M1i4Y3ETgfsrbiYD/3ADLKRHjr2TO5O6xUrWtfFh6aDR8fOSbVpm1qCSmxFGMaHq5QLJ3Ab0FQTKF/eFehogkzXb8opY/PlI9r+9DcUJ1epAjbNjzvHDDSEZxwi/i5kCNfxqnQNZHQ4uIgEysOk/kjBEtfISxyeD2PGYiyMYk9zMtEUk9LoUTR3/EXiFcJc4iw83DUVICbaCdMPh2ZRsv3A1CWx608rtIyF+qqKnmfX5me7njnYi0vGVDY97T4cV5rKrdZTTOZVggur2l+sPG+BJSYmEVqz3cZ81mVOr4znwU6w3f2e5HxD7ivdJJEz70xgPFX8pFruQulAOohd8qXakqdtA+ew+tr0h3M+cWvOu6VNXQlbijRgC4R89CclHW4/GX3j0OulJUotrV29rTpmVZ7MTGrnZkwJbNUYAe1GEFo7LNws+GJTcNM9R6QA/AYvJ2eE3SjE2G7VaIUh2RvSe2O094Ln7yIJctzEK8afiCiIQQnIgy/M+YheoC+TzogvLZGuNsvrt/oiiilUNa6WODTr1DmJGIyM4cg0pZuVKJ8dx+zf4l7+efkBOa/2mzU9DakvoRQK8/ClR6tuOAVXHZksPehcI3eTX/ZI0MtM2CLJouoi86hPbgwEorBt+nLClkw=",
  "File": "/app/basic-auth-sealed.yaml",
  "SymlinkFile": "",
  "Commit": "",
  "Entropy": 5.9583898,
  "Author": "",
  "Email": "",
  "Date": "",
  "Message": "",
  "Tags": [],
  "Fingerprint": "/app/basic-auth-sealed.yaml:generic-api-key:10"
 }
]
```
Simply running it with the previous version(v8.23.1) and the warning dissapears:
```bash
docker run --rm -it -v .:/app zricethezav/gitleaks:v8.23.1 detect --no-git --source /app/basic-auth-sealed.yaml -r /proc/1/fd/1
Unable to find image 'zricethezav/gitleaks:v8.23.1' locally
v8.23.1: Pulling from zricethezav/gitleaks
861950bce9fa: Already exists 
3545b3941889: Pull complete 
fc695bbd2920: Pull complete 
e56258af7c0d: Pull complete 
Digest: sha256:a695fbcee9f56b8f3d8a121caa078c2d8adbb31989cd28b213b90e336be2dbb9
Status: Downloaded newer image for zricethezav/gitleaks:v8.23.1

    ○
    │╲
    │ ○
    ○ ░
    ░    gitleaks

9:04PM INF scanned ~1721 bytes (1.72 KB) in 5.08ms
9:04PM INF no leaks found
[]
```
**Expected behavior**
These secrets are encrypted with the private key present in the cluster, so I expect them to not be detected as a gitleak since that is the purpuse of sealed secrets, just like in the previous version. 

**Screenshots**
I think it's not needed, but let me know if you need anything else!

**Basic Info (please complete the following information):**
 - OS: Running on a pipeline in Gitlab CI (or locally with docker in the steps to reproduce)
 - Gitleaks Version: [v8.23.2](https://hub.docker.com/layers/zricethezav/gitleaks/v8.23.2/images/sha256-767cb2abd3c70149b8090d8d6dd9c341da1226a92e3ceed0ddce9db55075b8c8)

**Additional context**
About Sealed Secrets: https://fluxcd.io/flux/guides/sealed-secrets/
I guess it's related to the change made to detect base64:

https://github.com/gitleaks/gitleaks/commit/f3ae52e13822075d6203fed93e89dc7c0258f205 feat(generic-api-key): detect base64 (https://github.com/gitleaks/gitleaks/pull/1598)

But if you try to base64decode that string, nothing useful comes out of it.

cc @zricethezav

Thanks in advance for your time!

**Comment by rgmz** [comment]
Hey @pvillaverde, as you mentioned this looks like an unfortunate byproduct of #1598. Previously, generic-api-key's pattern only contained a subset of valid base-64 characters (`[a-z0-9=]`), causing it to miss a substantial amount of valid secrets.

> But if you try to base64decode that string, nothing useful comes out of it.

Because Gitleaks' scanning is pattern-based, it can't differentiate between matches that _look like_ base64 encoding and ones that _are_.

Perhaps we could leverage @bplaxco's [work on decoding](https://github.com/gitleaks/gitleaks/releases/tag/v8.20.0) to create a feature that filters invalid base, however, that wouldn't help in this case. While the output may not be ASCII, that example **is** valid base64.

-------------------------

So, what can be done to eliminate or reduce these false positives? Without removing `+` and `/` from the pattern (which is my preference), we can try to ignore things that _look like_ sealed secrets with a custom allowlist.

Assumptions about SealedSecret values:
1. They're predominantly in `.yaml` files
2. They appear to always start with `Ag`
3. They tend to be quite long

```yaml
    password: AgAYsM4W6e5MMp90oqj7sIolG+//xxJTwRh8ke50CUFiZ8M/r5BoV/vHh3zKnlskt/s4jK058M1i4Y3ETgfsrbiYD/3ADLKRHjr2TO5O6xUrWtfFh6aDR8fOSbVpm1qCSmxFGMaHq5QLJ3Ab0FQTKF/eFehogkzXb8opY/PlI9r+9DcUJ1epAjbNjzvHDDSEZxwi/i5kCNfxqnQNZHQ4uIgEysOk/kjBEtfISxyeD2PGYiyMYk9zMtEUk9LoUTR3/EXiFcJc4iw83DUVICbaCdMPh2ZRsv3A1CWx608rtIyF+qqKnmfX5me7njnYi0vGVDY97T4cV5rKrdZTTOZVggur2l+sPG+BJSYmEVqz3cZ81mVOr4znwU6w3f2e5HxD7ivdJJEz70xgPFX8pFruQulAOohd8qXakqdtA+ew+tr0h3M+cWvOu6VNXQlbijRgC4R89CclHW4/GX3j0OulJUotrV29rTpmVZ7MTGrnZkwJbNUYAe1GEFo7LNws+GJTcNM9R6QA/AYvJ2eE3SjE2G7VaIUh2RvSe2O094Ln7yIJctzEK8afiCiIQQnIgy/M+YheoC+TzogvLZGuNsvrt/oiiilUNa6WODTr1DmJGIyM4cg0pZuVKJ8dx+zf4l7+efkBOa/2mzU9DakvoRQK8/ClR6tuOAVXHZksPehcI3eTX/ZI0MtM2CLJouoi86hPbgwEorBt+nLClkw=
    user: AgAMrlzJFHS+mqUhv2ZpG57VNoTSRrewuu6FZVPZcV35dCmdZwesz3MSrmweNHXAlJbVMSMRlINIEBQZKgjw0szEh2ZKkXjGv1926p34GJJSB5/rqYBIDUFkIRY3aJsijMN6etjLRQi68sbYIQAZQM4pGdN23++CfNmXoQgDm9ItspcSYAcOeKP8tZ799pQTdM1pMMur5EyrYWxckORCz+OT1+buCL9+5DJkjU7JuQCk5QkwXRE1sm76FvmmP+a3FbNCIgqsBpD42AqqD4/ex0PogKr7gDkG27MWZNIvCWDd2iF4x1cwJgOtNZJEzQ7tDr+Mf4438w03sJQPMtCEUuuzX1I7SPuT6D9eRSV00GA/IS0/fmNbPf2pPHFxj8t1RMsGI2ZLdZBOXapn3P0SLYZ2Xh6QIqdxzb3VR37WS/Ir4c8v86ZzDTbnqVdT/rwb7U4Iy2k3nDj+/ghxD+7HQbmBx4zzFVYe70Sb1QIWthzZHtuvoX7+FeSa6iU6ipUj4g0U9r53vD+AYt7ntJtCI3EdX+Fh9yJe4AAL4ToHjnt3s2EG4K5i0/21KwAy9WX2rkwBb8GD3POT3zZq2b4uB5gUYyF467kw0J7MfEsPJjAfhd72+IMM9BZDU4tlrFBJPRubVsmRJKelM/o1YTkbl+eFNyWBE1t5IQ9DFjHpcppgUm1CUiDdI0RbIc2goHfFWNePxZZQBg==
```

Thus, something like this _could_ work:
```toml
[extend]
useDefault = true

[[rules]]
id = "generic-api-key"
[[allowlists]]
condition = "AND"
regexes = ['''Ag[a-zA-Z0-9+/]{150,}={0,2}''']
paths = ['''(?i).*\.ya?ml$''']
```
