### ISSUE TITLE
The "generic-api-key" rule may raise false positive in vuejs files

### ISSUE THREAD

**Issue by arkokoo** [gitleaks/gitleaks#1762]
The "generic-api-key" rule triggered with the following snippet.

In a vue file, when a variable contains "Key" in it's variable name, directly followed by a dynamic property with at least 3 words, it seems to raise the false positive.

```vue
<my-custom-component v-model="anyValWithKeyInside" :followed-by-a-dynamic-attributes-with-at-least-two-dashes="true" />
```

I checked existing issues and didn't find my problem.

Is this a false positive that needs to be fixed or should I add a custom rule in my allowlist as a workaround ?

Reproduced on Gitleaks Version : v8.23.3

**Comment by rgmz** [comment]
> Is this a false positive that needs to be fixed or should I add a custom rule in my allowlist as a workaround ?

It is, though it may be a tricky one to fix. You can try something like this as a workaround in the interim:

```toml
[[rules]]
id = "generic-api-key"
[[rules.allowlists]]
regexTarget = "line"
regexes = ['''v-model="\w*key\*"''']
```

**Comment by arkokoo** [comment]
Ok, thanks, your regex didn't work for me so I tried another one:

[[rules]]
id = "generic-api-key"
[[rules.allowlists]]
regexTarget = "line"
regexes = ['''v-model="[^"]*[kK][Ee][Yy][^"]*"''']

**Comment by arkokoo** [comment]
Ok, thanks, your regex didn't work for me so I tried another one:

```toml
[[rules]]
id = "generic-api-key"
[[rules.allowlists]]
regexTarget = "line"
regexes = ['''v-model="[^"]*[kK][Ee][Yy][^"]*"''']
```

> > Is this a false positive that needs to be fixed or should I add a custom rule in my allowlist as a workaround ?
> 
> It is, though it may be a tricky one to fix. You can try something like this as a workaround in the interim:
> 
> [[rules]]
> id = "generic-api-key"
> [[rules.allowlists]]
> regexTarget = "line"
> regexes = ['''v-model="\w*key\*"''']
