### ISSUE TITLE
Usage via pre-commit.com does not work

### ISSUE THREAD

**Issue by guettli** [gitleaks/gitleaks#1781]
**Describe the bug**

I tried to use gitleaks via pre-commit.com

I used the config if your README.

I got:

```log
❯ pre-commit autoupdate
An error has occurred: InvalidConfigError: 
==> File .pre-commit-config.yaml
==> At Config()
==> At key: repos
==> At Repository(repo='https://github.com/pre-commit/pre-commit-hooks')
==> At key: hooks
==> At Hook(id=MISSING)
=====> Missing required key: id
Check the log at /home/guettli/.cache/pre-commit/pre-commit.log
```

```
❯ pre-commit -V
pre-commit 4.1.0
```

When I add an id:

```yaml
  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.24.0
    id: foo
    hooks:
      - id: gitleaks
````

```
❯ pre-commit autoupdate
[https://github.com/pre-commit/pre-commit-hooks] Cannot update because the update target is missing these hooks: foo

```

Other pre-commit hooks work fine.
**To Reproduce**

**Expected behavior**

**Screenshots**

**Basic Info (please complete the following information):**
 - OS:
 - Gitleaks Version:

**Additional context**

cc @zricethezav

**Comment by guettli** [comment]
I am sorry, this was an indentation bug. Now it works:

```yaml
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v5.0.0
  hooks:

  # Common hooks
  - id: trailing-whitespace
    exclude: ^vendor/
  - id: check-added-large-files
  - id: check-merge-conflict

- repo: https://github.com/gitleaks/gitleaks
  rev: v8.24.0
  hooks:
    - id: gitleaks

```
