### ISSUE TITLE
Support custom gitconfig

### ISSUE THREAD

**Issue by tj-smith47** [gitleaks/gitleaks#1814]
**Is your feature request related to a problem? Please describe.**
The problem I run into is when using gitleaks in a repo that uses sops encryption.

If you were to set `git config --global diff.sopsdiffer.textconv 'sops -d'`, and have a `.gitattributes` in each repository containing `*.enc.* diff=sopsdiffer`, it allows you to view diffs against sops encrypted files in clear text. However, this breaks gitleaks making it flag the decrypted contents of the encrypted file when the values it's flagging aren't what will actually be committed. Of course, the only way around this is that we prefix `SKIP=gitleaks` to a commit. It would be ideal if we could condition developers to trust that when an issue is reported, it's valid, rather than having to skip gitleaks everytime they modify an encoded secret value.

**Describe the solution you'd like**
Something to the effect of a `--git-config` flag to pass the location of a custom git config to reference throughout the lifecycle of a `gitleaks` scan / run.

**Describe alternatives you've considered**
A janky global pre-commit script that removes the config option, runs gitleaks, and then replaces it, but this should not be considered a resilient or reliable alternative. Just stating that I did put forth a bit of effort and came up short. That said, with a custom git config flag, I can just pass their global config to some temp file and rip out any mention of `sops`, then use that with gitleaks.

**Additional context**

cc @zricethezav

**Comment by jpbochi** [comment]
I ran into the same problem. My solution was to set `GIT_CONFIG_GLOBAL` to an empty value when calling `gitleaks`. [That var](https://git-scm.com/docs/git-var#Documentation/git-var.txt-GITCONFIGGLOBAL) is for the user config file. 

```sh
► git var GIT_CONFIG_GLOBAL
/home/jpbochi/.config/git/config
/home/jpbochi/.gitconfig

► GIT_CONFIG_GLOBAL= git var GIT_CONFIG_GLOBAL # the output of this is empty
```

**Comment by DamianFekete** [comment]
Maybe you can also use something like this if you don't want to replace the entire configuration (Assumes GIT_CONFIG_COUNT was not yet set):
```sh
$ GIT_CONFIG_COUNT=1 GIT_CONFIG_KEY_0=diff.sopsdiffer.textconv GIT_CONFIG_VALUE_0="/bin/cat" 
```

**Comment by andrii-kravets-x** [comment]
Currently this is the fix if you use with `pre-commit` tool
```yaml
  - repo: https://github.com/gitleaks/gitleaks
    rev: 83d9cd684c87d95d656c1458ef04895a7f1cbd8e # v8.30.1
    hooks:
      - id: gitleaks
        entry: bash -euo pipefail -c "GIT_CONFIG_COUNT=1 GIT_CONFIG_KEY_0=diff.sopsdiffer.textconv GIT_CONFIG_VALUE_0=cat gitleaks git --pre-commit --redact --staged --verbose"
```
